export const CMP_GRID_SHOW_DESTINATION_MODAL = 'CMP_GRID_SHOW_DESTINATION_MODAL';
export const CMP_GRID_HIDE_DESTINATION_MODAL = 'CMP_GRID_HIDE_DESTINATION_MODAL';
export const CMP_GRID_SHOW_CONTACT_MODAL = 'CMP_GRID_SHOW_CONTACT_MODAL';
export const CMP_GRID_HIDE_CONTACT_MODAL = 'CMP_GRID_HIDE_CONTACT_MODAL';
